// ui-react/src/pages/TrackSelector.tsx
import React from 'react';
import { List, Checkbox } from 'antd';
import { MediaFile } from 'a22-shared';

interface Props {
  tracks: MediaFile.Track[];
  selectedTracks: MediaFile.Track[];
  onChange: (selected: MediaFile.Track[]) => void;
}

const TrackSelector: React.FC<Props> = ({ tracks, selectedTracks, onChange }) => {
  const selectedIds = selectedTracks.map((t) => t.formatId);

  const toggle = (track: MediaFile.Track, checked: boolean) => {
    const newSelected = checked
      ? [...selectedTracks, track]
      : selectedTracks.filter((t) => t.formatId !== track.formatId);
    onChange(newSelected);
  };

  return (
    <List
      bordered
      dataSource={tracks}
      renderItem={(track) => (
        <List.Item key={track.formatId}>
          <Checkbox
            checked={selectedIds.includes(track.formatId)}
            onChange={(e) => toggle(track, e.target.checked)}
          >
            {track.format}
          </Checkbox>
        </List.Item>
      )}
    />
  );
};

export default TrackSelector;

// ui-vue/src/views/TrackSelector.vue
<!-- ui-vue/src/views/TrackSelector.vue -->
<template>
	<n-list bordered>
		<n-list-item v-for="(track, index) in tracks" :key="index">
			<n-checkbox
				:label="track.format"
				:checked="selectedIndexes.includes(index)"
				@update:checked="(checked) => toggleSelection(index, checked)"
			/>
		</n-list-item>
	</n-list>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { MediaFile } from 'a22-share';

const props = defineProps<{
	tracks: MediaFile.Track[];
	modelValue: MediaFile.Track[];
}>();

const emit = defineEmits(['update:modelValue']);

const selectedIndexes = ref<number[]>([]);

watch(
	() => props.modelValue,
	() => {
		selectedIndexes.value = props.tracks
			.map((track, i) => (props.modelValue.includes(track) ? i : -1))
			.filter(i => i !== -1);
	},
	{ immediate: true }
);

function toggleSelection(index: number, checked: boolean) {
	if (checked) {
		if (!selectedIndexes.value.includes(index)) {
			selectedIndexes.value.push(index);
		}
	} else {
		selectedIndexes.value = selectedIndexes.value.filter(i => i !== index);
	}
	emit('update:modelValue', selectedIndexes.value.map(i => props.tracks[i]));
}
</script>
