// ui-vue/src/views/Home.vue
<template>
	<div class="home-container">
		<div class="toolbar">
			<n-space justify="space-between">
				<div>
					<n-checkbox v-model:checked="selectAll" @update:checked="toggleSelectAll">
						Select All
					</n-checkbox>
				</div>
				<n-space>
					<n-button size="small" @click="downloadSelectedFiles" :disabled="!selectedFiles.length || isDownloading">
						Download
						<n-icon v-if="isDownloading">
							<loading />
						</n-icon>
					</n-button>
					<n-button size="small" type="error" @click="deleteSelectedFiles"
						:disabled="!selectedFiles.length || isDeleting">
						Delete
						<n-icon v-if="isDeleting">
							<loading />
						</n-icon>
					</n-button>
				</n-space>
			</n-space>
		</div>

		<n-list bordered>
			<n-list-item v-for="file in mediaFiles" :key="file.id">
				<n-collapse>
					<n-collapse-item>
						<!-- Заголовок плашки -->
						<template #header>
							<div class="list-item-header">
								<div class="header-left">
									<n-checkbox :checked="isSelected(file.id)" @update:checked="toggleSelectFile(file.id)" />
								</div>
								<div class="header-center">
									<div class="file-name">
										<n-ellipsis :line-clamp="2">{{ file.source.title }}</n-ellipsis>
									</div>

									<n-space size="small" align="center" wrap>
										<n-tag type="info" :bordered="false">{{ file.source.extractor }} : {{ file.source.id }}</n-tag>
										<!-- <n-tag type="info" :bordered="false">{{ file.source.id }}</n-tag> -->

										<n-tooltip trigger="hover">
											<template #trigger>
												<n-button quaternary size="tiny" @click.stop="copyUrl(file.source.webpageUrl)">
													<template #icon>
														<n-icon>
															<CopyOutline />
														</n-icon>
													</template>
												</n-button>
											</template>
											Copy URL to clipboard
										</n-tooltip>

										<n-tooltip trigger="hover">
											<template #trigger>
												<n-button quaternary size="tiny" @click.stop="openUrl(file.source.webpageUrl)">
													<template #icon>
														<n-icon>
															<OpenOutline />
														</n-icon>
													</template>
												</n-button>
											</template>
											Open in browser
										</n-tooltip>
									</n-space>

									<n-space size="small" wrap>
										<n-tooltip v-for="track in file.trackIds" :key="track.formatId" trigger="hover" placement="bottom">
											<template #trigger>
												<n-tag :type="getTrackType(track)" :bordered="false" size="small">
													<n-icon :component="CheckmarkCircle" />
													{{ track.formatId }}
												</n-tag>
											</template>
											<span>{{ track.format }} / {{ track.ext }}</span>
										</n-tooltip>
									</n-space>

								</div>

								<div class="header-right">
									<img :src="file.source.thumbnail" alt="Preview" v-if="file.source.thumbnail" />
									<div v-else class="no-preview">Нет превью</div>
								</div>
							</div>
						</template>

						<!-- Детали при раскрытии -->
						<div class="collapse-body">
							<MediaFileDetails :file="file" />
							<div class="edit-button">
								<n-button size="small" @click="configureFile(file)">Редактировать</n-button>
							</div>
						</div>
					</n-collapse-item>
				</n-collapse>
			</n-list-item>
		</n-list>
	</div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import {
	NButton,
	NList,
	NListItem,
	NCollapse,
	NCollapseItem,
	NCheckbox,
	NSpace,
	NIcon,
} from 'naive-ui';
import { useElectronBridge } from '../plugins/electron-bridge';
import type { MediaFile } from '../../shared/types/media-file';
import MediaFileDetails from './MediaFileDetails.vue';
import { CheckmarkCircle, CopyOutline, OpenOutline } from '@vicons/ionicons5'; // или любой другой набор иконок
import { useMessage } from 'naive-ui';



const router = useRouter();
const bridge = useElectronBridge();
const mediaFiles = ref<MediaFile.Data[]>([]);
const selectedIds = ref<Set<string>>(new Set());
const selectAll = ref(false);
const isDownloading = ref(false);
const isDeleting = ref(false);

onMounted(loadList);

async function loadList() {
	try {
		const list = await bridge.getList();
		mediaFiles.value = list;
	} catch (e) {
		console.error('Ошибка загрузки списка файлов', e);
	}
}

function toggleSelectFile(id: string) {
	if (selectedIds.value.has(id)) {
		selectedIds.value.delete(id);
	} else {
		selectedIds.value.add(id);
	}
}

function isSelected(id: string) {
	return selectedIds.value.has(id);
}

function toggleSelectAll(checked: boolean) {
	if (checked) {
		selectedIds.value = new Set(mediaFiles.value.map((f) => f.id));
	} else {
		selectedIds.value.clear();
	}
}

watch(selectAll, (val) => {
	if (val) {
		selectedIds.value = new Set(mediaFiles.value.map((f) => f.id));
	} else {
		selectedIds.value.clear();
	}
});

const selectedFiles = computed(() =>
	mediaFiles.value.filter((f) => selectedIds.value.has(f.id))
);

async function downloadSelectedFiles() {
	isDownloading.value = true;
	try {
		for (const file of selectedFiles.value) {
			alert(`Downloading ${file.fileName}`);
		}
	} finally {
		isDownloading.value = false;
	}
}

async function deleteSelectedFiles() {
	isDeleting.value = true;
	try {
		for (const file of selectedFiles.value) {
			// await bridge.deleteFile(file.id); // TODO: реализация на стороне Electron
		}
		await loadList();
	} finally {
		isDeleting.value = false;
	}
}

function configureFile(file: MediaFile.Data) {
	router.push({ name: 'task-settings', query: { id: file.id } });
}

function getTrackType(track: MediaFile.Track): 'success' | 'warning' | 'error' | 'default' {
	switch (true) {
		case track.hasVideo && track.hasAudio:
			return 'error';
		case track.hasVideo:
			return 'success';
		case track.hasAudio:
			return 'warning';
		default:
			return 'default';
	}
}

const message = useMessage();

function copyUrl(url: string) {
	navigator.clipboard.writeText(url).then(() => {
		message.success('Ссылка скопирована');
	}).catch(() => {
		message.error('Ошибка копирования');
	});
}

async function openUrl(url: string) {
	try {
		// await bridge.openExternal(url);
	} catch (e) {
		message.error('Не удалось открыть ссылку');
	}
}
</script>

<style scoped>
.home-container {
	margin-top: 20px;
}

.toolbar {
	margin-bottom: 12px;
}

.list-item-header {
	display: flex;
	align-items: flex-start;
	width: 100%;
	gap: 16px;
}

.header-left {
	padding-top: 4px;
}

.header-center {
	flex: 1;
	display: flex;
	flex-direction: column;
	gap: 4px;
	font-size: 14px;
}

.file-name {
	font-weight: 600;
}

.source-line {
	color: #888;
}

.track-ids {
	color: #444;
	font-size: 12px;
}

.header-right {
	width: 180px;
	height: 100px;
	background: #f5f5f5;
	display: flex;
	justify-content: center;
	align-items: center;
	overflow: hidden;
}

.header-right img {
	max-width: 100%;
	max-height: 100%;
	object-fit: contain;
}

.no-preview {
	font-size: 12px;
	color: #999;
	text-align: center;
}

.collapse-body {
	padding-top: 8px;
}

.edit-button {
	margin-top: 10px;
	text-align: right;
}
</style>

// ui-react/src/pages/Home.tsx
import React, { useEffect, useState, useMemo } from 'react';
import {
	Button,
	Checkbox,
	Col,
	Collapse,
	List,
	Row,
	Space,
	Tag,
	Tooltip,
	Typography,
	message,
} from 'antd';
import {
	CopyOutlined,
	EyeOutlined,
	LoadingOutlined,
} from '@ant-design/icons';
import { MediaFile } from 'a22-shared';
import MediaFileDetails from './MediaFileDetails';
import { useElectronBridge } from '../contexts/electronBridgeContext';
import './Home.css';
import { stopPropagation } from '../utils/events';

const { Paragraph } = Typography;

const Home: React.FC = () => {
	const [mediaFiles, setMediaFiles] = useState<MediaFile.Data[]>([]);
	const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
	const [selectAll, setSelectAll] = useState(false);
	const [isDownloading, setIsDownloading] = useState(false);
	const [isDeleting, setIsDeleting] = useState(false);

	const bridge = useElectronBridge();

	useEffect(() => {
		const loadList = async () => {
			try {
				const list = await bridge.getList();
				setMediaFiles(list);
			} catch (e) {
				console.error('Error loading file list', e);
			}
		};
		loadList();
	}, [bridge]);

	const toggleSelectAll = (checked: boolean) => {
		setSelectAll(checked);
		setSelectedIds(checked ? new Set(mediaFiles.map((f) => f.id)) : new Set());
	};

	const toggleSelectFile = (id: string) => {
		const updated = new Set(selectedIds);
		if (updated.has(id)) {
			updated.delete(id);
		} else {
			updated.add(id);
		}
		setSelectedIds(updated);
		setSelectAll(updated.size === mediaFiles.length);
	};

	const isSelected = (id: string) => selectedIds.has(id);

	const selectedFiles = useMemo(
		() => mediaFiles.filter((f) => selectedIds.has(f.id)),
		[mediaFiles, selectedIds]
	);

	const downloadSelectedFiles = async () => {
		setIsDownloading(true);
		try {
			for (const file of selectedFiles) {
				message.info(`Downloading ${file.fileName}`);
			}
		} finally {
			setIsDownloading(false);
		}
	};

	const deleteSelectedFiles = async () => {
		setIsDeleting(true);
		try {
			// await bridge.deleteFile(...) if implemented
			const list = await bridge.getList();
			setMediaFiles(list);
		} finally {
			setIsDeleting(false);
		}
	};

	const configureFile = (file: MediaFile.Data) => {
		console.log(`Navigating to task-settings for file ID: ${file.id}`);
	};

	const getTrackType = (track: MediaFile.Track): 'success' | 'warning' | 'error' | undefined => {
		if (track.hasVideo && track.hasAudio) return 'error';
		if (track.hasVideo) return 'success';
		if (track.hasAudio) return 'warning';
		return undefined;
	};

	const copyUrl = (url: string) => {
		navigator.clipboard
			.writeText(url)
			.then(() => message.success('Link copied'))
			.catch(() => message.error('Copy error'));
	};

	const openUrl = async (url: string) => {
		try {
			// await bridge.openExternal(url); // if available
			window.open(url, '_blank');
		} catch {
			message.error('Failed to open link');
		}
	};

	return (
		<div className="home-container">
			<div className="toolbar">
				<Row justify="space-between" align="middle">
					<Col>
						<Checkbox checked={selectAll} onChange={(e) => toggleSelectAll(e.target.checked)}>
							Select All
						</Checkbox>
					</Col>
					<Col>
						<Space>
							<Button
								size="small"
								onClick={downloadSelectedFiles}
								disabled={!selectedFiles.length || isDownloading}
								icon={isDownloading ? <LoadingOutlined /> : null}
							>
								Download
							</Button>
							<Button
								size="small"
								danger
								onClick={deleteSelectedFiles}
								disabled={!selectedFiles.length || isDeleting}
								icon={isDeleting ? <LoadingOutlined /> : null}
							>
								Delete
							</Button>
						</Space>
					</Col>
				</Row>
			</div>

			<List
				bordered
				dataSource={mediaFiles}
				renderItem={(file) => (
					<List.Item>
						<Collapse
							items={[
								{
									key: file.id,
									label: (
										<div className="list-item-header">
											<div className="header-left">
												<Checkbox
													checked={isSelected(file.id)}
													onClick={stopPropagation}
													onChange={() => toggleSelectFile(file.id)}
												/>
											</div>

											<div className="header-center">
												<div className="file-name">
													<Paragraph ellipsis={{ rows: 2 }}>{file.source.title}</Paragraph>
												</div>
												<Space size="small" align="center" wrap>
													<Tag color="blue">
														{file.source.extractor} : {file.source.id}
													</Tag>
													<Tooltip title="Copy URL to clipboard">
														<Button
															type="text"
															size="small"
															icon={<CopyOutlined />}
															onClick={(e) => {
																copyUrl(file.source.webpageUrl);
																stopPropagation(e);
															}}
														/>
													</Tooltip>
													{/* <Tooltip title="Open in browser">
														<Button
															type="text"
															size="small"
															icon={<EyeOutlined />}
															onClick={(e) => {
																openUrl(file.source.webpageUrl);
																stopPropagation(e);
															}}
														/>
													</Tooltip> */}
												</Space>
												<Space size="small" wrap>
													{file.trackIds.map((track) => (
														<Tooltip
															key={track.formatId}
															title={`${track.format} / ${track.ext}`}
															placement="bottom"
														>
															<Tag color={getTrackType(track)} icon={<CheckmarkCircle />}>
																{track.formatId}
															</Tag>
														</Tooltip>
													))}
												</Space>
											</div>

											<div className="header-right">
												{file.source.thumbnail ? (
													<img src={file.source.thumbnail} alt="Preview" />
												) : (
													<div className="no-preview">No preview</div>
												)}
											</div>
										</div>
									),
									children: (
										<div className="collapse-body">
											<MediaFileDetails file={file} />
											{/* <div className="edit-button">
												<Button size="small" onClick={() => configureFile(file)}>
													Edit
												</Button>
											</div> */}
										</div>
									),
								},
							]}
						/>
					</List.Item>
				)}
			/>
		</div>
	);
};

const CheckmarkCircle: React.FC = () => <span>✓</span>;

export default Home;
